# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  $puppet = <<PUPPET
  sudo dnf install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
  sudo dnf install -y puppet
PUPPET

  $modulesweb = <<MODULESWEB
puppet module install puppetlabs-docker
sudo cp -vR ~/.puppetlabs/etc/code/modules/ /etc/puppetlabs/code/
MODULESWEB


  # Puppet Server - CentOS Stream 8
  config.vm.define "server" do |server|
    server.vm.box = "shekeriev/centos-stream-8"
    server.vm.hostname = "puppet-server"
    server.vm.network "private_network", ip: "192.168.99.100"
    server.vm.provision "shell", path: "add_hosts.sh"
    server.vm.provision "shell", inline: $puppet, privileged: false
    server.vm.provision "shell", inline: $modulesweb, privileged: false

    server.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "default.pp"
      puppet.options = "--verbose --debug"
    end
  


    server.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 1
    end
  

 
  
  end
end

  