# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

$puppet = <<PUPPET
  sudo dnf install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
  sudo dnf install -y puppet
PUPPET

$modulesweb = <<MODULESWEB
  puppet module install puppetlabs-firewall
  sudo cp -vR ~/.puppetlabs/etc/code/modules/ /etc/puppetlabs/code/
MODULESWEB

$modulesdb = <<MODULESDB
  puppet module install puppetlabs/mysql
  puppet module install puppetlabs-firewall
sudo cp -vR ~/.puppetlabs/etc/code/modules/ /etc/puppetlabs/code/
MODULESDB


  # WEB - CentOS Stream 8
  config.vm.define "client1" do |client1|
    client1.vm.box = "shekeriev/centos-stream-8"
    client1.vm.hostname = "web"
    client1.vm.network "private_network", ip: "192.168.99.101"
    client1.vm.provision "shell", path: "add_hosts.sh"
    client1.vm.provision "shell", inline: $puppet, privileged: false
    client1.vm.provision "shell", inline: $modulesweb, privileged: false

    client1.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "web.pp"
      puppet.options = "--verbose --debug"
    end

    client1.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end
  end

  # DB - CentOS Stream 8
  config.vm.define "client2" do |client2|
    client2.vm.box = "shekeriev/centos-stream-8"
    client2.vm.hostname = "db"
    client2.vm.network "private_network", ip: "192.168.99.102"
    client2.vm.provision "shell", path: "add_hosts.sh"
    client2.vm.provision "shell", inline: $puppet, privileged: false
    client2.vm.provision "shell", inline: $modulesdb, privileged: false

    client2.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "db.pp"
      puppet.options = "--verbose --debug"
    end

    client2.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end
  end
  
end

  